echo '[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  external_node_modules = ["@netlify/neon"]
  node_bundler = "esbuild"' > netlify.toml
